
                  





        .global	_PowerON_Reset                                                                                                                  


        .global	_Manual_Reset                                                                                                                   


        .global         _TBL_Reset                                                                                                                      



        .global         _INT_TLBMiss_Load

        .global         _INT_TLBMiss_Store

        .global         _INT_TLBInitial_Page

        .global         _INT_TLBProtect_Load

        .global         _INT_TLBProtect_Store

        .global         _INT_Address_load

        .global         _INT_Address_store

        .global         _INT_FPU

        .global         _INT_Reserved140

        .global         _INT_TRAPA

        .global         _INT_Illegal_code

        .global         _INT_Illegal_slot

        .global         _INT_NMI

        .global         _INT_User_Break

        .global         _INT_Extern_0000

        .global         _INT_Extern_0001

        .global         _INT_Extern_0010

        .global         _INT_Extern_0011

        .global         _INT_Extern_0100

        .global         _INT_Extern_0101

        .global         _INT_Extern_0110

        .global         _INT_Extern_0111

        .global         _INT_Extern_1000

        .global         _INT_Extern_1001

        .global         _INT_Extern_1010

        .global         _INT_Extern_1011

        .global         _INT_Extern_1100

        .global         _INT_Extern_1101

        .global         _INT_Extern_1110

        .global         _INT_Reserved3E0

        .global         _INT_Timer_Under_0

        .global         _INT_Timer_Under_1

        .global         _INT_Timer_Under_2

        .global         _INT_Input_Capture

        .global         _INT_RTC_ATI

        .global         _INT_RTC_PRI

        .global         _INT_RTC_CUI

        .global         _INT_SCI_ERI

        .global         _INT_SCI_RXI

        .global         _INT_SCI_TXI

        .global         _INT_SCI_TEI

        .global         _INT_WDT

        .global         _INT_REF_RCMI

        .global         _INT_REF_ROVI

        .global         _INT_Reserved5C0

        .global         _INT_Reserved5E0

        .global         _INT_HUDI

        .global         _INT_Reserved620

        .global         _INT_DMAC_DMTE0

        .global         _INT_DMAC_DMTE1

        .global         _INT_DMAC_DMTE2

        .global         _INT_DMAC_DMTE3

        .global         _INT_DMAC_DMAE

        .global         _INT_Reserved6E0

        .global         _INT_SCIF_ERI

        .global         _INT_SCIF_RXI

        .global         _INT_SCIF_BRI

        .global         _INT_SCIF_TXI

        .global         _INT_DMAC_DMTE4

        .global         _INT_DMAC_DMTE5

        .global         _INT_DMAC_DMTE6

        .global         _INT_DMAC_DMTE7

        .global         _INT_Illegal_FPU

        .global         _INT_Illegal_slot_FPU

        .global         _INT_Reserved840

        .global         _INT_Reserved860

        .global         _INT_Reserved880

        .global         _INT_Reserved8A0

        .global         _INT_Reserved8C0

        .global         _INT_Reserved8E0

        .global         _INT_Reserved900

        .global         _INT_Reserved920

        .global         _INT_Reserved940

        .global         _INT_Reserved960

        .global         _INT_Reserved980

        .global         _INT_Reserved9A0

        .global         _INT_Reserved9C0

        .global         _INT_Reserved9E0

        .global         _INT_PCIC_PCISERR

        .global         _INT_PCIC_PCIDMA3

        .global         _INT_PCIC_PCIDMA2

        .global         _INT_PCIC_PCIDMA1

        .global         _INT_PCIC_PCIDMA0

        .global         _INT_PCIC_PCIPWON

        .global         _INT_PCIC_PCIPWDWN

        .global         _INT_PCIC_PCIERR

        .global         _INT_Timer_Under_3

        .global         _INT_ReservedB20

        .global         _INT_ReservedB40

        .global         _INT_ReservedB60

        .global         _INT_Timer_Under_4
